name: InfiniteTicker
author: rpflo
category: Effects
tags: [ticker, widget, fx.scroll]
docs: http://moodocs.net/rpflo/mootools-rpflo/InfiniteTicker
demo: http://mootools.net/shell/rpflo/qFu99/embedded/result,js,html,css
current: 0.8